(defglobal
  ?*PRIORITY-PDDL-INSTANCES* = -5100
  ?*PRIORITY-PDDL-GET-ACTION-NAMES* = -5300
  ?*PRIORITY-PDDL-OBJECTS* = -5400
  ?*PRIORITY-PDDL-FLUENTS* = -5500
  ?*PRIORITY-PDDL-APPLY-EFFECT* = -5600
  ?*PRIORITY-PDDL-CLEAR-GOALS* = -5700
  ?*PRIORITY-PDDL-SET-GOALS* = -5800
  ?*PRIORITY-PDDL-CHECK-PRECONDITION* = -5900
  ?*PRIORITY-PDDL-GET-FLUENTS* = -6000
)
