clips_manager:
  ros__parameters:
    environments: ["task3"]
    task3:
      plugins: ["executive", "ros_msgs", "files"]
      log_clips_to_file: true
      watch: ["facts", "rules"]

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    ros_msgs:
      plugin: "cx::RosMsgsPlugin"
    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["labcegor_bringup"]
      batch: [
        "clips/labcegor_bringup/task3/task3.clp"]
