(defrule move-robot-to
  (protobuf-peer (name ROBOT1) (peer-id ?peer-id))
  ?move_base <- (move_base (state PRE) (depend_on) (from ?from) (from_side ?from_side) (task_id ?id))
  ; ES darf keine andere move_base geben die im aktiven verfahren ist also alle anderen dürfen nur FINSIHED und PRE sein
  (not (move_base (state ?s&: (not (or (eq ?s FINISHED) (eq ?s PRE))))))
  (game-state (team-color ?team&: (neq ?team NOT-SET)))
=>
  (printout blue "MOVING ROBOT1 TO " ?from " AT SIDE " ?from_side crlf)

  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" ?team)
  (pb-set-field ?msg "task_id" (+ (* ?id 10) 1))
  (pb-set-field ?msg "robot_id" 1)
  (bind ?move-msg (pb-create "llsf_msgs.Move"))
  (pb-set-field ?move-msg "waypoint" ?from)
  (pb-set-field ?move-msg "machine_point" ?from_side)
  (pb-set-field ?msg "move" ?move-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
  (pb-destroy ?move-msg)
  (modify ?move_base (state MOVING_FROM))
)

(defrule grasp-robot
  (protobuf-peer (name ROBOT1) (peer-id ?peer-id))
  ?move_base <- (move_base (state MOVED_FROM) (depend_on) (from ?from) (from_side ?from_side) (task_id ?id))
  (game-state (team-color ?team&: (neq ?team NOT-SET)))
  =>
  (printout blue "GRASPING ROBOT1 AT " ?from " AT SIDE " ?from_side crlf)
  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" ?team)
  (pb-set-field ?msg "task_id" (+ (* ?id 10) 2))
  (pb-set-field ?msg "robot_id" 1)
  (bind ?retrieve-msg (pb-create "llsf_msgs.Retrieve"))
  (pb-set-field ?retrieve-msg "machine_id" ?from)
  (pb-set-field ?retrieve-msg "machine_point" ?from_side)
  (pb-set-field ?msg "retrieve" ?retrieve-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
  (pb-destroy ?retrieve-msg)
  (modify ?move_base (state GRIPPING))
)

(defrule move-robot-target
  (protobuf-peer (name ROBOT1) (peer-id ?peer-id))
  ?move_base <- (move_base (state GRIPPED) (depend_on) (target ?target)
   (target_side ?target_side) (task_id ?id))
  (game-state (team-color ?team&: (neq ?team NOT-SET)))
  =>
  (printout blue "MOVING ROBOT1 TO " ?target " AT SIDE " ?target_side crlf)

  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" ?team)
  (pb-set-field ?msg "task_id" (+ (* ?id 10) 3))
  (pb-set-field ?msg "robot_id" 1)
  (bind ?move-msg (pb-create "llsf_msgs.Move"))
  (pb-set-field ?move-msg "waypoint" ?target)
  (pb-set-field ?move-msg "machine_point" ?target_side)
  (pb-set-field ?msg "move" ?move-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
  (pb-destroy ?move-msg)
  (modify ?move_base (state MOVING_TARGET))
)

(defrule place-robot-target
  (protobuf-peer (name ROBOT1) (peer-id ?peer-id))
  ?move_base <- (move_base (state MOVED_TARGET) (depend_on) (target ?target)
   (target_side ?target_side) (task_id ?id))
  (game-state (team-color ?team&: (neq ?team NOT-SET)))
  =>
  (printout blue "PUTTING ROBOT1 AT " ?target " AT SIDE " ?target_side crlf)

  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" ?team)
  (pb-set-field ?msg "task_id" (+ (* ?id 10) 3))
  (pb-set-field ?msg "robot_id" 1)
  (bind ?deliver-msg (pb-create "llsf_msgs.Deliver"))
  (pb-set-field ?deliver-msg "machine_id" ?target)
  (pb-set-field ?deliver-msg "machine_point" ?target_side)
  (pb-set-field ?msg "retrieve" ?retrieve-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
  (pb-destroy ?deliver-msg)
  (modify ?move_base (state PUTTING))
)
