;----WARNING --- WIP------
(defrule robo_move
  ?ac <- (action (a_type "m") (id ?id) (machine ?wp) (io ?io) (task_id ?t-id) (wait ?w))
  ;(done (done_t_id ?w))
  (protobuf-peer (name ?name) (peer-id ?peer-id))
  (test (eq ?name (sym-cat (str-cat "ROBOT" ?id))))
  ;old;?lt <-(last_task (id ?id) (l_task_id ?last_t))
  ;old;?do <- (do (id ?id) (task ?t-id))
  =>
  ;TODO renew ;(assert (robo_busy (id ?id)))
  (retract ?ac)
  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" MAGENTA)
  (pb-set-field ?msg "task_id" ?t-id)
  (modify ?lt (l_task_id ?t-id)); UPdate fact (maybe in check funktion)
  (pb-set-field ?msg "robot_id" ?id)
  (bind ?move-msg (pb-create "llsf_msgs.Move")) 
  (pb-set-field ?move-msg "waypoint" ?wp)
  (pb-set-field ?move-msg "machine_point" ?io)
  (pb-set-field ?msg "move" ?move-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
)

(defrule robo_retrive
  ?ac <- (action (a_type "r") (id ?id) (machine ?wp) (io ?io) (task_id ?t-id)(wait ?w))
  ;(done (done_t_id ?w))
  (robo_status (id ?id) (pos ?wp) (pos_at_waypoint ?io))
  (protobuf-peer (name ?name) (peer-id ?peer-id))
  (test (eq ?name (sym-cat (str-cat "ROBOT" ?id))))
  ;old;?lt <-(last_task (id ?id) (l_task_id ?last_t))
  ;old;?do <- (do (id ?id) (task ?t-id))
  =>
  (retract ?ac)
  ;TODO renew ;(assert (robo_busy (id ?id)))
  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" MAGENTA)
  (pb-set-field ?msg "task_id" ?t-id)
  (modify ?lt (l_task_id ?t-id)); UPdate fact (maybe in check funktion)
  (pb-set-field ?msg "robot_id" ?id)
  (bind ?retrieve-msg (pb-create "llsf_msgs.Retrieve")) 
  (pb-set-field ?retrieve-msg "machine_id" ?wp)
  (pb-set-field ?retrieve-msg "machine_point" ?io)
  (pb-set-field ?msg "retrieve" ?retrieve-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
)


(defrule robo_deliver
  ?ac <- (action (a_type "d") (id ?id) (machine ?wp) (io ?io) (task_id ?t-id)(wait ?w))
  ;(done (done_t_id ?w))
  (robo_status (id ?id) (pos ?wp) (pos_at_waypoint ?io))
  (protobuf-peer (name ?name) (peer-id ?peer-id))
  (test (eq ?name (sym-cat (str-cat "ROBOT" ?id))))
  ;old;?pay_rs1 <- (payments (station 1) (total_in ?t_in1) (current_in ?c_in1))
  ;old;?pay_rs2 <- (payments (station 2) (total_in ?t_in2) (current_in ?c_in2))
  ;old;?lt <-(last_task (id ?id) (l_task_id ?last_t))
  ;old;?do <- (do (id ?id) (task ?t-id))
  =>
  (retract ?ac)
  ;TODO renew ;(assert (robo_busy (id ?id)))
  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" MAGENTA)
  (pb-set-field ?msg "task_id" ?t-id)
  (modify ?lt (l_task_id ?t-id)); UPdate fact (maybe in check funktion)
  (pb-set-field ?msg "robot_id" ?id)
  (bind ?deliver-msg (pb-create "llsf_msgs.Deliver")) 
  (pb-set-field ?deliver-msg "machine_id" ?wp)
  (pb-set-field ?deliver-msg"machine_point" ?io)
  (if (eq ?io "slide")
    (update_rs)
  )
  (pb-set-field ?msg "deliver" ?deliver-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
)

(defrule machine-instruct
  (protobuf-peer (name refbox-private) (peer-id ?peer-id))
  ?inst <- (instruct (machine ?m) (operation ?op) (task_id ?t-id) (wait ?w))
  ;(done (done_t_id ?w))
  ;(not (machine_busy (id ?m)))
  ;?lt <-(last_task (id 4) (l_task_id ?last_t))
  =>
  (assert (machine_busy (id ?m)))
  (modify ?lt (l_task_id ?t-id))
  (bind ?msg (pb-create "llsf_msgs.PrepareMachine"))
  (pb-set-field ?msg "team_color" MAGENTA)
  (pb-set-field ?msg "machine" ?m)
  (if (or (eq ?m "M-CS1") (eq ?m "M-CS2"))
    then
      (bind ?prep-msg (pb-create "llsf_msgs.PrepareInstructionCS")) 
      (pb-set-field ?prep-msg "operation" ?op)
      (pb-set-field ?msg "instruction_cs" ?prep-msg)
  )
  
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
)