;----WARNING --- WIP------
(defrule robo_move
  ?ac <- (action (a_type "m") (id ?id) (machine ?wp) (io ?io) (task_id ?t-id) (wait ?w))
  ;(done (done_t_id ?w))
  (protobuf-peer (name ?name) (peer-id ?peer-id))
  (test (eq ?name (sym-cat (str-cat "ROBOT" ?id))))
  ;old;?lt <-(last_task (id ?id) (l_task_id ?last_t))
  ;old;?do <- (do (id ?id) (task ?t-id))
  =>
  ;TODO renew ;(assert (robo_busy (id ?id)))
  (retract ?ac)
  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" MAGENTA)
  (pb-set-field ?msg "task_id" ?t-id)
  ; OLD (modify ?lt (l_task_id ?t-id)); UPdate fact (maybe in check funktion)
  (pb-set-field ?msg "robot_id" ?id)
  (bind ?move-msg (pb-create "llsf_msgs.Move")) 
  (pb-set-field ?move-msg "waypoint" ?wp)
  (pb-set-field ?move-msg "machine_point" ?io)
  (pb-set-field ?msg "move" ?move-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
)

(defrule robo_retrive
  ?ac <- (action (a_type "r") (id ?id) (machine ?wp) (io ?io) (task_id ?t-id))
  ;(done (done_t_id ?w))
  (robo_status (id ?id) (pos ?wp) (pos_at_waypoint ?p_at_wp))
  (test (or (eq ?io ?p_at_wp) (and (eq ?p_at_wp INPUT) (eq ?io SHELF))))
  (protobuf-peer (name ?name) (peer-id ?peer-id))
  (test (eq ?name (sym-cat (str-cat "ROBOT" ?id))))
  ;old;?lt <-(last_task (id ?id) (l_task_id ?last_t))
  ;old;?do <- (do (id ?id) (task ?t-id))
  =>
  (retract ?ac)
  ;TODO renew ;(assert (robo_busy (id ?id)))
  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" MAGENTA)
  (pb-set-field ?msg "task_id" ?t-id)
  ; OLD (modify ?lt (l_task_id ?t-id)); UPdate fact (maybe in check funktion)
  (pb-set-field ?msg "robot_id" ?id)
  (bind ?retrieve-msg (pb-create "llsf_msgs.Retrieve")) 
  (pb-set-field ?retrieve-msg "machine_id" ?wp)
  (pb-set-field ?retrieve-msg "machine_point" ?io)
  (pb-set-field ?msg "retrieve" ?retrieve-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
)


(defrule robo_deliver
  ?ac <- (action (a_type "d") (id ?id) (machine ?wp) (io ?io) (task_id ?t-id))
  ;(done (done_t_id ?w))
  (robo_status (id ?id) (pos ?wp) (pos_at_waypoint ?p_at_wp))
  (test (or (eq ?io ?p_at_wp) (and (eq ?p_at_wp INPUT) (eq ?io SLIDE))))
  (protobuf-peer (name ?name) (peer-id ?peer-id))
  (test (eq ?name (sym-cat (str-cat "ROBOT" ?id))))
  ;old;?pay_rs1 <- (payments (station 1) (total_in ?t_in1) (current_in ?c_in1))
  ;old;?pay_rs2 <- (payments (station 2) (total_in ?t_in2) (current_in ?c_in2))
  ;old;?lt <-(last_task (id ?id) (l_task_id ?last_t))
  ;old;?do <- (do (id ?id) (task ?t-id))
  =>
  (retract ?ac)
  ;TODO renew ;(assert (robo_busy (id ?id)))
  (bind ?msg (pb-create "llsf_msgs.AgentTask"))
  (pb-set-field ?msg "team_color" MAGENTA)
  (pb-set-field ?msg "task_id" ?t-id)
  ; OLD (modify ?lt (l_task_id ?t-id)); UPdate fact (maybe in check funktion)
  (pb-set-field ?msg "robot_id" ?id)
  (bind ?deliver-msg (pb-create "llsf_msgs.Deliver")) 
  (pb-set-field ?deliver-msg "machine_id" ?wp)
  (pb-set-field ?deliver-msg "machine_point" ?io)
  (if (eq SLIDE ?io)
    then
      (printout red ?io crlf)
      (if(eq ?wp M-RS1)
        then
          (assert (update_rs (id 1) (payment 1)))
        else
          (assert (update_rs (id 2) (payment 1)))
      )
    else
  )
  (pb-set-field ?msg "deliver" ?deliver-msg)
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
)

(defrule machine-instruct
  (protobuf-peer (name refbox-private) (peer-id ?peer-id))
  ?inst <- (instruct (machine ?m) (operation ?op) (color ?c) (task_id ?t-id) (wait ?w) (oder_id ?o_id))
  ;(test (member$ ?m (create$ M-BS M-CS1 M-CS2 M-BS) ))
  ?m_sate <- (machine_status (name ?m) (slide_shelf ?pay_in))
  (ring-spec (color ?ca) (cost ?ring_cost))
  (test (or (not (member$ ?c (create$ RING_BLUE RING_ORANGE RING_GEEEN RING_YELLOW)))
                  (eq ?c ?ca)))
  ;(test ((>= ?pay_in ?ring_cost)))
  (machine (name ?m) (zone ~NOT-SET))
  (test (or (not (or (eq ?m M-RS1) (eq ?m M-RS2))) (>= ?pay_in ?ring_cost)) ) 
  =>
  (retract ?inst)
  (modify ?m_sate (task 97) (order ?o_id) (pos INPUT)) ;task 97 is hotfix maybe change later, should not be needed else where apart form wait for check
  ; OLD (assert (machine_busy (id ?m)))
  ;Old (modify ?lt (l_task_id ?t-id))
  (bind ?msg (pb-create "llsf_msgs.PrepareMachine"))
  (pb-set-field ?msg "team_color" MAGENTA)
  (pb-set-field ?msg "machine" ?m)
  (if (or (eq ?m M-CS1) (eq ?m M-CS2))
    then
      ;
      (bind ?prep-msg (pb-create "llsf_msgs.PrepareInstructionCS")) 
      (pb-set-field ?prep-msg "operation" ?op)
      (pb-set-field ?msg "instruction_cs" ?prep-msg)
  )
  (if(eq ?m M-BS)
    then
      ;(printout green "reached if in machine instruct" crlf)
      (bind ?prep-msg (pb-create "llsf_msgs.PrepareInstructionBS")) 
      (pb-set-field ?prep-msg "side" ?op)
      (pb-set-field ?prep-msg "color" ?c)
      (pb-set-field ?msg "instruction_bs" ?prep-msg)
  )
  (pb-broadcast ?peer-id ?msg)
  (pb-destroy ?msg)
  ;(printout green "message sent" crlf)
)
